#C++ is obviously significantly better... but Python is fun
print("TTTTT")
print("  T  ")
print("  T  ")
print("  T  ")
print("  T  ")
print("  T  ")
print(       )
print("  SSS  ")
print(" S   S ")
print(" S     ")
print("  SSS  ")
print("     S ")
print(" S   S ")
print("  SSS  ")
